version: "3.3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3308:3306"
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - graphql-task-network

  backend:
    image: graphql-task:latest
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - graphql-task-network
    depends_on:
      - "db"

volumes:
  mysql:
networks:
  graphql-task-network:
    driver: bridge
